/**
 * @fileoverview GitHub Issue creation and webhook delivery for pipeline reports.
 * Renders a structured markdown summary of all dependency analysis results and
 * posts it as a GitHub Issue. Optionally delivers a short-form notification to
 * a Discord webhook or an ntfy.sh topic.
 */

import { DRY_RUN_PREFIX, NOTIFIER, PR, RECOMMENDATION } from "./constants.js";
import { logger } from "./logger.js";

/**
 * @typedef {import('./analyzer.js').RiskScore} RiskScore
 */

/**
 * @typedef {object} DependencyReport
 * @property {string} owner - GitHub repository owner
 * @property {string} repo - GitHub repository name
 * @property {string} scannedAt - ISO 8601 timestamp of when the scan ran
 * @property {RiskScore[]} results - Analyzed package updates
 */

// ── Rendering ─────────────────────────────────────────────────────────────────

/** Maps recommendation values to emoji badges for the issue body. */
const RECOMMENDATION_BADGE = /** @type {const} */ ({
  [RECOMMENDATION.THUMBS_UP]: "✅ Auto-approve",
  [RECOMMENDATION.THUMBS_DOWN]: "🚫 Skip",
  [RECOMMENDATION.NEEDS_REVIEW]: "⚠️ Review needed",
});

/** Maps update type to a short label used in the summary table. */
const UPDATE_TYPE_LABEL = /** @type {const} */ ({
  patch: "Patch",
  minor: "Minor",
  major: "**Major**",
});

/**
 * Renders a markdown issue body from a dependency report.
 * Exported for unit testing.
 *
 * @param {DependencyReport} report
 * @returns {string}
 */
export function renderIssueBody(report) {
  const { owner, repo, scannedAt, results } = report;

  const thumbsUp = results.filter((r) => r.recommendation === RECOMMENDATION.THUMBS_UP).length;
  const needsReview = results.filter((r) => r.recommendation === RECOMMENDATION.NEEDS_REVIEW).length;
  const thumbsDown = results.filter((r) => r.recommendation === RECOMMENDATION.THUMBS_DOWN).length;

  const lines = [
    `## Dependency Update Report — \`${owner}/${repo}\``,
    "",
    `> Scanned at: ${scannedAt}`,
    "",
    "### Summary",
    "",
    `| Metric | Count |`,
    `| --- | --- |`,
    `| Total outdated | ${results.length} |`,
    `| ✅ Auto-approve | ${thumbsUp} |`,
    `| ⚠️ Needs review | ${needsReview} |`,
    `| 🚫 Skip | ${thumbsDown} |`,
    "",
    "### Package Details",
    "",
    "| Package | Current | Latest | Type | Risk | Recommendation |",
    "| --- | --- | --- | --- | --- | --- |",
    ...results.map((r) =>
      `| \`${r.packageName}\` | \`${r.currentVersion}\` | \`${r.latestVersion}\` | ${UPDATE_TYPE_LABEL[r.updateType] ?? r.updateType} | ${r.riskScore} | ${RECOMMENDATION_BADGE[r.recommendation] ?? r.recommendation} |`
    ),
  ];

  // Breaking changes section — only included when at least one exists.
  const withBreaking = results.filter((r) => r.breakingChanges.length > 0);
  if (withBreaking.length > 0) {
    lines.push("", "### Breaking Changes", "");
    for (const r of withBreaking) {
      lines.push(`#### \`${r.packageName}\` ${r.currentVersion} → ${r.latestVersion}`, "");
      for (const change of r.breakingChanges) {
        lines.push(`- ${change}`);
      }
      lines.push("");
    }
  }

  lines.push(
    "---",
    "**To approve updates and open a PR:** comment `APPROVE`  ",
    "**To skip this cycle:** comment `SKIP`",
    "",
    "_Generated by [dep-bot](https://github.com) — automated dependency management pipeline._"
  );

  if (report.notifyUser) {
    lines.push("", `cc @${report.notifyUser}`);
  }

  return lines.join("\n");
}

// ── GitHub Issue ──────────────────────────────────────────────────────────────

/**
 * Finds the most recent dep-bot report issue for this repo updated within the
 * last 48 hours, regardless of open/closed state. This allows the approval gate
 * to find issues that were closed by the owner immediately after approving.
 *
 * @param {object} params
 * @param {import('@octokit/rest').Octokit} params.octokit
 * @param {string} params.owner
 * @param {string} params.repo
 * @returns {Promise<{ issueNumber: number; issueUrl: string } | null>}
 */
async function findExistingReportIssue({ octokit, owner, repo }) {
  const { data: issues } = await octokit.rest.issues.listForRepo({
    owner,
    repo,
    state: "all",
    labels: PR.LABELS.join(","),
    sort: "updated",
    direction: "desc",
    per_page: 10,
  });

  const cutoff = new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString();
  const existing = issues.find(
    (i) => i.title.startsWith(NOTIFIER.ISSUE_TITLE_PREFIX) && i.updated_at >= cutoff
  );
  if (!existing) return null;

  logger.info(
    { owner, repo, issueNumber: existing.number, state: existing.state },
    "Found recent dep-bot issue — reusing instead of creating a new one"
  );
  return { issueNumber: existing.number, issueUrl: existing.html_url };
}

/**
 * Creates (or reuses) a structured GitHub Issue containing the full dependency
 * report. If an open dep-bot issue already exists for this repo, its body is
 * updated in-place and the same issue number is returned — this prevents the
 * approval gate from losing track of prior APPROVE/SKIP comments when the bot
 * is re-triggered.
 *
 * Returns null in dry-run mode without making any API calls.
 *
 * @param {object} params
 * @param {import('@octokit/rest').Octokit} params.octokit
 * @param {string} params.owner
 * @param {string} params.repo
 * @param {DependencyReport} params.report
 * @param {boolean} params.dryRun
 * @returns {Promise<{ issueNumber: number; issueUrl: string } | null>}
 */
export async function createReportIssue({ octokit, owner, repo, report, dryRun }) {
  const title = `${NOTIFIER.ISSUE_TITLE_PREFIX} — ${new Date(report.scannedAt).toISOString().slice(0, 10)}`;
  const body = renderIssueBody(report);

  if (dryRun) {
    logger.info({ owner, repo, title }, `${DRY_RUN_PREFIX} Skipping issue creation`);
    return null;
  }

  // Reuse an existing open issue so APPROVE comments are preserved across re-triggers.
  const existing = await findExistingReportIssue({ octokit, owner, repo });
  if (existing) {
    await octokit.rest.issues.update({
      owner,
      repo,
      issue_number: existing.issueNumber,
      title,
      body,
    });
    logger.info({ owner, repo, issueNumber: existing.issueNumber }, "Updated existing dep-bot issue");
    return existing;
  }

  logger.info({ owner, repo }, "Creating dependency report issue");

  const { data } = await octokit.rest.issues.create({
    owner,
    repo,
    title,
    body,
    labels: PR.LABELS,
  });

  logger.info({ owner, repo, issueNumber: data.number, issueUrl: data.html_url }, "Issue created");
  return { issueNumber: data.number, issueUrl: data.html_url };
}

// ── Webhook notifications ─────────────────────────────────────────────────────

/**
 * Delivers a notification payload to a Discord webhook or ntfy.sh topic.
 * Either or both targets may be configured; absent targets are silently skipped.
 * Failures are logged as warnings — a notification error must never halt the pipeline.
 *
 * @param {object} params
 * @param {string | undefined} params.discordWebhook - Full Discord webhook URL
 * @param {string | undefined} params.ntfyTopic - ntfy.sh topic name (not the full URL)
 * @param {string} params.message
 * @returns {Promise<void>}
 */
export async function sendWebhookNotification({ discordWebhook, ntfyTopic, message }) {
  const tasks = [];

  if (discordWebhook) {
    const truncated = message.length > NOTIFIER.DISCORD_CONTENT_LIMIT
      ? `${message.slice(0, NOTIFIER.DISCORD_CONTENT_LIMIT - 3)}...`
      : message;

    tasks.push(
      fetch(discordWebhook, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content: truncated }),
      })
        .then((resp) => {
          if (!resp.ok) {
            logger.warn({ status: resp.status }, "Discord webhook delivery failed");
          } else {
            logger.debug("Discord webhook delivered");
          }
        })
        .catch((error) => {
          logger.warn({ error: error.message }, "Discord webhook fetch threw an error");
        })
    );
  }

  if (ntfyTopic) {
    tasks.push(
      fetch(`${NOTIFIER.NTFY_BASE_URL}/${ntfyTopic}`, {
        method: "POST",
        body: message,
      })
        .then((resp) => {
          if (!resp.ok) {
            logger.warn({ status: resp.status }, "ntfy.sh delivery failed");
          } else {
            logger.debug("ntfy.sh notification delivered");
          }
        })
        .catch((error) => {
          logger.warn({ error: error.message }, "ntfy.sh fetch threw an error");
        })
    );
  }

  await Promise.all(tasks);
}
