/**
 * @fileoverview Branch creation and pull request publishing.
 * Creates a per-run branch from the repo's default branch, then opens a
 * structured PR summarising every dependency change in the run.
 */

import { DRY_RUN_PREFIX, PR } from "./constants.js";
import { logger } from "./logger.js";

/**
 * @typedef {import('./notifier.js').DependencyReport} DependencyReport
 * @typedef {import('./analyzer.js').RiskScore} RiskScore
 */

// ── PR body rendering ─────────────────────────────────────────────────────────

/** Risk score band labels used in the PR body table. */
const riskBand = (score) => {
  if (score <= 30) return `🟢 ${score}`;
  if (score <= 70) return `🟡 ${score}`;
  return `🔴 ${score}`;
};

/**
 * Renders a concise markdown PR body from a dependency report.
 * Exported as a pure helper for unit testing.
 *
 * @param {DependencyReport} report
 * @param {boolean} hasSecurityFixes
 * @param {boolean} [qaFailed] - When true, adds a build-failure warning (draft PR scenario)
 * @returns {string}
 */
export function renderPrBody(report, hasSecurityFixes, qaFailed = false) {
  const lines = [
    `## Automated Dependency Updates`,
    "",
  ];

  if (qaFailed) {
    lines.push(
      "> 🚧 **Build failed after applying these updates.**",
      ">",
      "> This PR was opened as a **draft** because the build or test suite did not pass after",
      "> the dependency update was applied. The changes here are the raw version bumps only —",
      "> you will need to address any breaking changes before marking this ready for review.",
      ""
    );
  }

  if (hasSecurityFixes) {
    lines.push("> ⚠️ **This PR includes security-relevant updates.** Review breaking changes carefully.", "");
  }

  lines.push(
    "### Changes",
    "",
    "| Package | From | To | Type | Risk |",
    "| --- | --- | --- | --- | --- |",
    ...report.results.map((r) =>
      `| \`${r.packageName}\` | \`${r.currentVersion}\` | \`${r.latestVersion}\` | ${r.updateType} | ${riskBand(r.riskScore)} |`
    ),
    "",
    "---",
    "_Generated by [dep-bot](https://github.com) — automated dependency management pipeline._"
  );

  return lines.join("\n");
}

// ── Branch creation ───────────────────────────────────────────────────────────

/**
 * Resolves the SHA of the tip of the repo's default branch.
 *
 * @param {import('@octokit/rest').Octokit} octokit
 * @param {string} owner
 * @param {string} repo
 * @returns {Promise<{ sha: string; defaultBranch: string }>}
 */
async function getDefaultBranchSha(octokit, owner, repo) {
  const { data: repoData } = await octokit.rest.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;

  const { data: refData } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  });

  return { sha: refData.object.sha, defaultBranch };
}

/**
 * Creates a new branch for the dependency update run.
 * Appends a numeric suffix (-2, -3 …) if the branch name is already taken,
 * up to 10 attempts before throwing.
 *
 * @param {object} params
 * @param {import('@octokit/rest').Octokit} params.octokit
 * @param {string} params.owner
 * @param {string} params.repo
 * @param {string} params.date - ISO date string YYYY-MM-DD, used in the branch name
 * @param {boolean} [params.dryRun]
 * @returns {Promise<string>} The created branch name
 */
export async function createUpdateBranch({ octokit, owner, repo, date, dryRun = false }) {
  const { sha: baseSha } = await getDefaultBranchSha(octokit, owner, repo);
  const baseName = `${PR.BRANCH_PREFIX}${date}`;

  if (dryRun) {
    logger.info({ owner, repo, baseName }, `${DRY_RUN_PREFIX} Skipping branch creation`);
    return baseName;
  }

  for (let attempt = 1; attempt <= 10; attempt++) {
    const branchName = attempt === 1 ? baseName : `${baseName}-${attempt}`;

    try {
      await octokit.rest.git.createRef({
        owner,
        repo,
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      });
      logger.info({ owner, repo, branchName }, "Update branch created");
      return branchName;
    } catch (error) {
      if (error.status === 422) {
        logger.debug({ owner, repo, branchName }, "Branch already exists — trying next suffix");
        continue;
      }
      throw error;
    }
  }

  throw new Error(
    `Failed to create a unique update branch for ${owner}/${repo} on ${date} after 10 attempts`
  );
}

// ── Branch deletion ───────────────────────────────────────────────────────────

/**
 * Deletes a branch from the remote repository.
 * Silently no-ops in dry-run mode. Logs a warning on failure rather than
 * throwing — a cleanup failure must never mask the original error.
 *
 * @param {object} params
 * @param {import('@octokit/rest').Octokit} params.octokit
 * @param {string} params.owner
 * @param {string} params.repo
 * @param {string} params.branch
 * @param {boolean} [params.dryRun]
 * @returns {Promise<void>}
 */
export async function deleteUpdateBranch({ octokit, owner, repo, branch, dryRun = false }) {
  if (dryRun) return;

  try {
    await octokit.rest.git.deleteRef({ owner, repo, ref: `heads/${branch}` });
    logger.info({ owner, repo, branch }, "Stale update branch deleted");
  } catch (err) {
    logger.warn({ owner, repo, branch, error: err.message }, "Failed to delete stale update branch");
  }
}

// ── Pull request ──────────────────────────────────────────────────────────────

/**
 * Opens a pull request with a structured summary of all dependency changes.
 * Adds the security label when at least one update is security-relevant.
 * Returns null in dry-run mode without making any API calls.
 *
 * @param {object} params
 * @param {import('@octokit/rest').Octokit} params.octokit
 * @param {string} params.owner
 * @param {string} params.repo
 * @param {string} params.branch - Head branch created by createUpdateBranch
 * @param {DependencyReport} params.report
 * @param {boolean} params.hasSecurityFixes
 * @param {boolean} [params.draft] - When true, opens the PR as a draft (build-failure scenario)
 * @param {boolean} [params.qaFailed] - Passed through to renderPrBody for the failure banner
 * @param {boolean} [params.dryRun]
 * @returns {Promise<{ prNumber: number; prUrl: string } | null>}
 */
export async function openPullRequest({
  octokit,
  owner,
  repo,
  branch,
  report,
  hasSecurityFixes,
  draft = false,
  qaFailed = false,
  dryRun = false,
}) {
  const { defaultBranch } = await getDefaultBranchSha(octokit, owner, repo);

  const title = draft
    ? `${PR.TITLE_PREFIX} [build failed — needs manual fix]`
    : hasSecurityFixes
      ? `${PR.TITLE_PREFIX} (security)`
      : PR.TITLE_PREFIX;

  const body = renderPrBody(report, hasSecurityFixes, qaFailed);

  if (dryRun) {
    logger.info({ owner, repo, branch, title, draft }, `${DRY_RUN_PREFIX} Skipping PR creation`);
    return null;
  }

  const { data } = await octokit.rest.pulls.create({
    owner,
    repo,
    title,
    body,
    head: branch,
    base: defaultBranch,
    labels: PR.LABELS,
    draft,
  });

  logger.info({ owner, repo, prNumber: data.number, prUrl: data.html_url, draft }, "Pull request opened");

  if (hasSecurityFixes) {
    await octokit.rest.issues.addLabels({
      owner,
      repo,
      issue_number: data.number,
      labels: [PR.SECURITY_LABEL],
    });
    logger.debug({ owner, repo, prNumber: data.number }, "Security label applied");
  }

  return { prNumber: data.number, prUrl: data.html_url };
}
